on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
    types: [checks_requested]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix build
      - run: nix flake check
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.head_ref || github.ref }}
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.head_ref || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: env
      - run: nix run .#deploy
